name: Weekly Snippets Discussion Creation
on:
  workflow_dispatch:
  schedule:
  - cron: 0 8 * * 2  # Every Tuesday at 08:00 UTC

permissions:
  discussions: write
  contents: read

jobs:
  weekly_discussion:    
    name: Create new discussion
    runs-on: ubuntu-latest
    steps:
  
    - name: Set Date
      # TODO: increment day of week
      run: echo "DATE=$(date -u '+%F')" >> $GITHUB_ENV
    - name: Get template
      uses: imjohnbo/extract-issue-template-fields@v1.0.1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/snippets.md # Core snippet details
        result-encoding: string
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Discussion
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = `RLT Snippets for ${{ env.DATE }}`;

          # TODO: Add your own ids here
          const repository_id = "";
          const category_id = "";

          const query = `
            mutation {
                createDiscussion(input:{repositoryId: "${repository_id}", categoryId: "${category_id}", title: "${title}", body: "${{ steps.extract.outputs.body }}"}) {
                  discussion { id, title }
                }
            }`;
          
          const {createDiscussion: { discussion }} = await github.graphql(
            query, {
              headers: {
                "GraphQL-Features": "discussions_api",
              },
          });
          console.log(`Created discussion with id ${discussion.id}`); 
